Repository grafana/grafana-polystat-panel, pull requests merged in 2020-01, with the labels that each got.

#89 Thresholds: add (optional) global threshold setting
  src/ctrl.ts
  src/metric_overrides_manager.ts
  src/module.ts
  src/partials/editor.options.html
  src/partials/editor.overrides.html
  src/partials/thresholds.html
  src/threshold_processor.ts
  src/thresholdsCtrl.ts
  src/tooltip.ts
  src/types.ts
Labels: effort/small, enhancement

#50 updates for issue 37
  .circleci/config.yml
  CHANGELOG.md
  jest.config.js
  package.json
  src/ctrl.ts
  src/partials/editor.options.html
  src/tooltip.ts
  src/utils.ts
Labels: enhancement

#96 metric and override enhancements
  .theia/settings.json
  src/composites_manager.ts
  src/metric_overrides_manager.ts
  src/partials/editor.composites.html
Labels: effort/medium
